### ISSUE TITLE
Error on startup: Native module cannot be null

### ISSUE THREAD

**Issue by jimgreer** [expo/playlist-example#19]
I'm getting this error on startup: 

```
Native module cannot be null.

NativeEventEmitter
    NativeEventEmitter.js:35:16
EventEmitter
    EventEmitter.js:21:48
<unknown>
    Location.js:8:46
loadModuleImplementation
    require.js:214:12
<unknown>
    Expo.js:5
loadModuleImplementation
    require.js:214:12
<unknown>
    AppEntry.js:1
loadModuleImplementation
    require.js:214:12
guardedLoadModule
    require.js:141:45
global code
    <unknown file>:0

**Comment by shareef301** [comment]
same here. can't figure out what to do 🤔

**Comment by a3l5o7n9** [comment]
Try updating the 'app.json' file line 7 - "sdkVersion": "30.0.0".
They updated it in 'package.json', but probably forgot that one.
Had the same issue until I found a thread with someone with a similar issue who just updated to v 30.0.0 and was advised to check that file.

**Comment by natterstefan** [comment]
Thank you @a3l5o7n9, helped me a lot. I still had to tweak some minor things to get it running. You can find my code (if anybody is interested) here: https://github.com/natterstefan/playlist-example/tree/feature/expo-sdk-31.

**Comment by steve1000** [comment]
For anyone else having this issue: we solved it because after upgrading to v31, even though the npm install created the split up of the expo modules, it didn't add them to the Podfile and header paths for the Xcode project.

Adding:
`
pod 'EXLocation',
    :path => "../node_modules/expo-location/ios"
`
To your pod file and `"${PODS_ROOT}/Headers/Public/EXLocation"` to the Header Search Paths on your Xcode project target should sort out this error.

Keep in mind it may not be the last of the errors that you'll see. If you create a fresh expo project and do an eject, have a look at the generated Podfile and Header Search Paths that are created. They'll probably have a lot more entries than your current config.

**Comment by cruzach** [comment]
Closing this as we've updated to SDK 34 and I wasn't able to repro this. If you run into any issues using the Audio API, please open any further issues at the main [Expo repo](https://github.com/expo/expo/issues)
