### ISSUE TITLE
No sound on iOS

### ISSUE THREAD

**Issue by THook** [expo/playlist-example#2]
The app doesn't output any sound on 10.0.2

**Comment by ramadis** [comment]
Hey @THook,

Try switching the [iphone ring/silent switch](http://www.any-data-recovery.com/images/tips/iphone/iphone-5-ring-silent-switch.jpg) to ring. I was having the same issue and it was that. Apparently, on older versions of the SDK (and by default in the newer ones) this was the expected behavior.

**Comment by gkufera** [comment]
Thanks @ramadis!

@THook in SDK >15, we provide the [audio mode API](https://docs.expo.io/versions/v17.0.0/sdk/audio.html), in which you can set `playsInSilentLockedModeIOS` to `true`.

Thanks!

Greg

**Comment by anasqadrei** [comment]
When I lock the iPhone it stops playing even if I set `playsInSilentLockedModeIOS` to `true`.  😔
